run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: portfolio

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - staticcheck
  disable-all: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck